# Generated by Django 4.2.7 on 2025-11-20 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('alert_type', models.CharField(choices=[('intrusion', 'Intrusion Attempt'), ('malware', 'Malware Detection'), ('ddos', 'DDoS Attack'), ('port_scan', 'Port Scan'), ('brute_force', 'Brute Force'), ('suspicious_traffic', 'Suspicious Traffic'), ('data_exfiltration', 'Data Exfiltration'), ('unauthorized_access', 'Unauthorized Access')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10, null=True)),
                ('signature', models.CharField(blank=True, max_length=200, null=True)),
                ('rule_id', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('timestamp', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['severity', 'timestamp'], name='security_al_severit_24f662_idx'), models.Index(fields=['status', 'timestamp'], name='security_al_status_b5f4d0_idx'), models.Index(fields=['alert_type', 'timestamp'], name='security_al_alert_t_52d059_idx'), models.Index(fields=['source_ip', 'timestamp'], name='security_al_source__649829_idx')],
            },
        ),
    ]
