# Generated by Django 4.2.7 on 2025-11-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('FTP', 'FTP'), ('SSH', 'SSH'), ('DNS', 'DNS'), ('DHCP', 'DHCP')], max_length=10)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('packets_sent', models.IntegerField(default=0)),
                ('packets_received', models.IntegerField(default=0)),
                ('connection_state', models.CharField(choices=[('ESTABLISHED', 'Established'), ('SYN_SENT', 'Syn Sent'), ('SYN_RECV', 'Syn Received'), ('FIN_WAIT', 'Fin Wait'), ('TIME_WAIT', 'Time Wait'), ('CLOSE', 'Close'), ('LISTEN', 'Listen')], default='ESTABLISHED', max_length=20)),
                ('duration', models.FloatField(default=0.0)),
                ('application', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'network_traffic',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='network_tra_timesta_27a714_idx'), models.Index(fields=['source_ip', 'timestamp'], name='network_tra_source__043d36_idx'), models.Index(fields=['destination_ip', 'timestamp'], name='network_tra_destina_40436a_idx'), models.Index(fields=['protocol', 'timestamp'], name='network_tra_protoco_46d9e2_idx')],
            },
        ),
    ]
