# Generated by Django 4.2.7 on 2025-11-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('hash', 'File Hash'), ('email', 'Email Address')], max_length=20)),
                ('ioc_value', models.CharField(max_length=500)),
                ('threat_type', models.CharField(choices=[('malware', 'Malware'), ('phishing', 'Phishing'), ('botnet', 'Botnet'), ('c2', 'Command & Control'), ('exploit', 'Exploit'), ('ransomware', 'Ransomware'), ('trojan', 'Trojan'), ('spyware', 'Spyware')], max_length=50)),
                ('description', models.TextField()),
                ('reputation_score', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=100)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'threat_intelligence',
                'ordering': ['-reputation_score', '-last_seen'],
                'indexes': [models.Index(fields=['ioc_type', 'ioc_value'], name='threat_inte_ioc_typ_9a3ea0_idx'), models.Index(fields=['threat_type', 'reputation_score'], name='threat_inte_threat__4fb7e4_idx'), models.Index(fields=['is_active', 'last_seen'], name='threat_inte_is_acti_24af68_idx')],
                'unique_together': {('ioc_type', 'ioc_value')},
            },
        ),
    ]
